name: Substitute Secrets into Tokenised File
description: Substitute GitHub Secrets into a File, matching on a specified Token format.
author: Skylark @ Lambdaspire
inputs:
  file:
    required: true
    description: The file to replace.
  output:
    required: false
    description: An optional alternative output file.
  tokenPattern:
    required: true
    description: A pattern to match tokens. Must contain the word TOKEN. e.g. '#{TOKEN}#', '${TOKEN}', '<<<TOKEN>>>'...
  secretsJson:
    required: true
    description: JSON representation of the secrets.
runs:
  using: node16
  main: dist/index.js
branding:
  icon: dollar-sign
  color: gray-dark